<h5> 
    <font size = 6 > 
    <font color = green>    
   <h1> Class Imbalance : undersampling </h1>
        
        
    

In [163]:
import os 
import pandas as pd 
import numpy as np 
from time import time
import multiprocessing as mp
from multiprocessing import Process, current_process 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix,cohen_kappa_score
import time




In [166]:
iphone_df = pd.read_csv(r"iphone_smallmatrix_labeled_9d.csv")


In [167]:
iphone_df['iphonesentiment'].value_counts()

5    7540
0    1962
4    1439
3    1188
2     454
1     390
Name: iphonesentiment, dtype: int64

In [168]:
minority = len(iphone_df[iphone_df['iphonesentiment'] == 1])

In [169]:
dic = { 0: 0, 1:0, 2:0, 3:0, 4:0, 5:0 }

for i in range(6):
    dic[i]= iphone_df[iphone_df['iphonesentiment'] == i].index
    print(dic[i])
    

Int64Index([    0,     1,     2,     3,     4,     7,     8,     9,    11,
               12,
            ...
            12867, 12871, 12885, 12906, 12914, 12919, 12923, 12934, 12950,
            12969],
           dtype='int64', length=1962)
Int64Index([ 824,  825,  827,  828,  829,  830,  831,  832,  833,  834,
            ...
            1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1306, 1308],
           dtype='int64', length=390)
Int64Index([  103,   154,   310,   333,   450,   550,   591,   666,   884,
             1028,
            ...
            10926, 11099, 11132, 11397, 11711, 11887, 11973, 12000, 12442,
            12726],
           dtype='int64', length=454)
Int64Index([   10,    71,    74,   109,   138,   146,   149,   218,   258,
              264,
            ...
            12750, 12751, 12752, 12757, 12797, 12824, 12887, 12895, 12918,
            12941],
           dtype='int64', length=1188)
Int64Index([    5,     6,    77,   126,   143,   156,   194,   207,   

In [170]:
dic_ind = { 0: 0, 1:0, 2:0, 3:0, 4:0, 5:0 }

for i in range(6):
    dic_ind[i] = np.random.choice(dic[i],minority,replace=False)
    

In [1]:
 under_sample_indices = np.concatenate((dic_ind[0],dic_ind[1],dic_ind[2],dic_ind[3],dic_ind[4],dic_ind[5]), axis=0,  )

NameError: name 'dic_ind' is not defined

In [172]:
under_sample_df = iphone_df.loc[under_sample_indices]

In [173]:
def X_Y_split(df,label):
    
    X= df.loc[:,df.columns != label ]
    y = df[label]
    
    return X,y 

    
    

In [174]:
X_og,y_og = X_Y_split(iphone_df,'iphonesentiment')

X_us,y_us = X_Y_split(under_sample_df,'iphonesentiment')

In [175]:
print(y_og.value_counts())
print("\n")
print(y_us.value_counts())

5    7540
0    1962
4    1439
3    1188
2     454
1     390
Name: iphonesentiment, dtype: int64


5    390
3    390
1    390
4    390
2    390
0    390
Name: iphonesentiment, dtype: int64


In [176]:

X_train_og , X_test_og , y_train_og , y_test_og =  train_test_split(X_og, y_og, test_size=0.33, random_state=42)



In [160]:
iphone_df['iphonesentiment'].value_counts()

5    7540
0    1962
4    1439
3    1188
2     454
1     390
Name: iphonesentiment, dtype: int64

In [ ]:
weights = np.zeros(leny_train)

weights[y_train == 1 ] = 5 



In [178]:
start_time = time.time()

rf = RandomForestClassifier(  )

rf.fit(X_train_og,y_train_og)

predictions = rf.predict(X_test_og)

end_time = start_time - time.time()

print("--- Run Time is : %s mins--- \n " % np.round(((time.time()-start_time)/60),2))
print("Accuracy : ",accuracy_score(predictions,y_test_og))
print("\n")

print("Kappa's : ",cohen_kappa_score(predictions,y_test_og))

print("\n")
print("Confusion Matrix : \n \n  ",confusion_matrix(predictions,y_test_og) )


NameError: name 'weights' is not defined

In [ ]:
 [ 386    0    1    3    6   11]
 [   1    0    0    0    1    3]
 [   0    1   21    0    1    6]
 [   3    0    1  273    2   10]
 [   4    1    1    4  156   37]
 [ 221  112  138  119  326 2433]

In [161]:
y_test_og.value_counts()

5    2500
0     615
4     492
3     399
2     162
1     114
Name: iphonesentiment, dtype: int64

In [44]:
X_train_us, X_test_us, y_train_us, y_test_us=  train_test_split(X_us, y_us, test_size=0.33, random_state=42)


In [45]:
start_time = time.time()

rf = RandomForestClassifier()

rf.fit(X_train_us,y_train_us)

predictions = rf.predict(X_test_us)

end_time = start_time - time.time()

print("--- Run Time is : %s mins--- \n " % np.round(((time.time()-start_time)/60),2))
print("Accuracy : ",accuracy_score(predictions,y_test_us))
print("\n")

print("Kappa's : ",cohen_kappa_score(predictions,y_test_us))

print("\n")
print("Confusion Matrix : \n \n  ",confusion_matrix(predictions,y_test_us) )


--- Run Time is : 0.0 mins--- 
 
Accuracy :  0.46054333764553684


Kappa's :  0.3547824694496433


Confusion Matrix : 
 
   [[88  0  2  0  4  1]
 [13 27 16  7  3 23]
 [ 1  4 29  4  8 13]
 [ 1  6  7 83  4  1]
 [ 7  8  2  4 50  5]
 [26 90 67 28 62 79]]


In [46]:
start_time = time.time()

rf = RandomForestClassifier()

rf.fit(X_us,y_us)

predictions = rf.predict(X_test_og)

end_time = start_time - time.time()

print("--- Run Time is : %s mins--- \n " % np.round(((time.time()-start_time)/60),2))
print("Accuracy : ",accuracy_score(predictions,y_test_og))
print("\n")

print("Kappa's : ",cohen_kappa_score(predictions,y_test_og))

print("\n")
print("Confusion Matrix : \n \n  ",confusion_matrix(predictions,y_test_og) )


--- Run Time is : 0.01 mins--- 
 
Accuracy :  0.6057916861279776


Kappa's :  0.4062462623498534


Confusion Matrix : 
 
   [[ 390    0    0    4    4   26]
 [  53   43   21   21   59  517]
 [  16    1   54   12   28  162]
 [   9    1    0  278    8   30]
 [  14    4    5    4  197  133]
 [ 133   65   82   80  196 1632]]


<h5> 
    <font size = 4> 
      We can see that despite moving our errors from the majority class we still got worse results anyways   
      Let's try to cut off only the 5 reviews to around 1500 so it's more balanced

In [144]:
index_5 = iphone_df[iphone_df['iphonesentiment'] == 5].index


index = np.random.choice(index_5,1500,replace=False)




In [145]:
index_dic = {0:0,1:0,2:0,3:0,4:0 }

for i in range(5):
    index_dic[i] = iphone_df[iphone_df['iphonesentiment'] == i].index
    
    
    

In [146]:
under_sample_indices = np.concatenate((index_dic[0],index_dic[1],index_dic[2],index_dic[3],
                                       index_dic[4],index ), axis=0,  )






new_us =  iphone_df.loc[under_sample_indices] 



In [147]:
X_nus,y_nus = X_Y_split(new_us,'iphonesentiment')

In [148]:
y_nus.value_counts()

0    1962
5    1500
4    1439
3    1188
2     454
1     390
Name: iphonesentiment, dtype: int64

In [150]:
X_train_nus, X_test_nus, y_train_nus, y_test_nus=  train_test_split(X_nus, y_nus, test_size=0.33, random_state=42)



In [151]:
y_test_nus.value_counts()

0    673
5    486
4    457
3    397
2    151
1    124
Name: iphonesentiment, dtype: int64

In [156]:
start_time = time.time()

rf = RandomForestClassifier()

rf.fit(X_train_nus,y_train_nus)

predictions = rf.predict(X_test_nus)

end_time = start_time - time.time()

print("--- Run Time is : %s mins--- \n " % np.round(((time.time()-start_time)/60),2))
print("Accuracy : ",accuracy_score(predictions,y_test_nus))
print("\n")

print("Kappa's : ",cohen_kappa_score(predictions,y_test_nus))

print("\n")
print("Confusion Matrix : \n \n  ",confusion_matrix(predictions,y_test_nus) )


--- Run Time is : 0.01 mins--- 
 
Accuracy :  0.5690559440559441


Kappa's :  0.4482660119460907


Confusion Matrix : 
 
   [[445   2   7   8  16  12]
 [  5   1   3   4   2  12]
 [  1   2  21   1   4   8]
 [  9   5   6 262   8  16]
 [ 24  12  16  17 173  38]
 [189 102  98 105 254 400]]


In [155]:
predictions = rf.predict(X_test_og)

end_time = start_time - time.time()

print("--- Run Time is : %s mins--- \n " % np.round(((time.time()-start_time)/60),2))
print("Accuracy : ",accuracy_score(predictions,y_test_og))
print("\n")

print("Kappa's : ",cohen_kappa_score(predictions,y_test_og))

print("\n")
print("Confusion Matrix : \n \n  ",confusion_matrix(predictions,y_test_og) )


--- Run Time is : 7.23 mins--- 
 
Accuracy :  0.2933208780943484


Kappa's :  0.20149986245221574


Confusion Matrix : 
 
   [[ 447   18   17   13   40  393]
 [   8   18    3    5    5   86]
 [   5    2   48    3    8   93]
 [   5    1    0  296    4   90]
 [ 150   75   94   82  435 1826]
 [   0    0    0    0    0   12]]


In [153]:
print(y_test_og.value_counts())

print("\n")



print(y_test_nus.value_counts())




5    2500
0     615
4     492
3     399
2     162
1     114
Name: iphonesentiment, dtype: int64


0    673
5    486
4    457
3    397
2    151
1    124
Name: iphonesentiment, dtype: int64


<h5> 
    <font size = 6 > 
    <font color = green>    
   <h1> Class Imbalance : Oversampling </h1>
        
        
    

In [ ]:
iphone_df = pd.read_csv(r"iphone_smallmatrix_labeled_9d.csv")


In [ ]:
iphone_df['iphonesentiment'].value_counts()

In [ ]:
from imblearn.over_sampling import SMOTE

# Resample the minority class. You can change the strategy to 'auto' if you are not sure.
sm = SMOTE(sampling_strategy='auto', random_state=7)

# Fit the model to generate the data.
oversampled_trainX, oversampled_trainY = sm.fit_sample(credit_df.drop('Class', axis=1), credit_df['Class'])
oversampled_train = pd.concat([pd.DataFrame(oversampled_trainY), pd.DataFrame(oversampled_trainX)], axis=1)
oversampled_train.columns = normalized_df.columns